### ISSUE TITLE
No such file or directory hamster_key2

### ISSUE THREAD

**Issue by BillGoobs** [ryanmurakami/hbfl#1]
C:\AWSDev\Code\scripts\module_02>node create-ec2-instance.js
Failed to create instance with: { Error: ENOENT: no such file or directory, open 'C:\Users\xxxxx\.ssh\hamster_key2'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\xxxxx\\.ssh\\hamster_key2' }

I'm not using an Apple device.  I'm using a Windows 10 machine.

In order for this to work correctly, I needed to comment out line 17.
//.then(helpers.persistKeyPair)

What is this doing?

**Comment by ryanmurakami** [comment]
Hi @BillGoobs, 
Ah, that function is trying to save the keypair locally. I believe the issue is that you may not have an `.ssh` folder in your home directory. In fact, since Windows doesn't have ssh, that's probably the issue. You can try creating a folder in your home directory called `.ssh` and that should fix it. I can update the code later to create the directory if it isn't found.

Thanks for creating the issue!

**Comment by guitarhero23** [comment]
Just ran into the same thing and that did indeed fix it, note I had to delete the previous resources it created since it was then claiming i had duplicate security groups and duplicate key pairs which was failing since the script was able to create them in AWS prior to failing due to no .ssh folder
